Repository badgerloop-software/pod-dashboard, pull requests merged in 2019-04, with the labels that each got.

#43 Basic PR Template
  .github/pull_request_template.md
Labels: enhancement

#44 Styling updates
  Exports/1235.json
  src/index.html
  src/public/images/disconnected.svg
  src/public/images/pod.png
  src/public/javascripts/charthandling.js
  src/public/javascripts/dynamicloading.js
  src/public/stylesheets/main.css
Labels: enhancement

#46 Add real battery values to tables
  src/database.json
  src/public/javascripts/dynamicloading.js
  src/testPodServer.js
Labels: enhancement

#47 Braking Values Filled
  src/database.json
  src/public/javascripts/main.js
Labels: enhancement

#49 Connection indicators
  Exports/1235.json
  Exports/281937.json
  Exports/28208.json
  src/constants.json
  src/database.json
  src/index.html
  src/public/javascripts/charthandling.js
  src/public/javascripts/communication.js
  src/public/javascripts/config.js
  src/public/javascripts/datainterfacing.js
  src/public/javascripts/dynamicloading.js
  src/public/javascripts/handler.js
  src/public/javascripts/main.js
  src/public/javascripts/testingtool.js
  src/public/stylesheets/main.css
Labels: Big, enhancement

#48 Switching states
  src/index.html
  src/public/javascripts/communication.js
  src/public/javascripts/dynamicloading.js
  src/public/javascripts/handler.js
  src/public/stylesheets/main.css
  src/testPodServer.js
Labels: Big, enhancement

#54 Filling json
  src/database.json
Labels: enhancement

#55 Fix Testpodserver
  src/database.json
  src/testPodServer.js
Labels: bug

#58 Bug fixes and polish
  src/public/javascripts/handler.js
  src/public/javascripts/main.js
  src/public/stylesheets/main.css
  src/public/stylesheets/main.grid.css
Labels: bug, enhancement

#59 Backend rework
  .gitignore
  src/database.json
  src/index.html
  src/public/javascripts/communication.js
  src/public/javascripts/datainterfacing.js
  src/public/javascripts/dynamicloading.js
  src/public/javascripts/handler.js
  src/public/stylesheets/main.css
  src/public/stylesheets/main.grid.css
  src/public/stylesheets/testingtool.grid.css
  src/testPodServer.js
  src/testing.html
Labels: Big, enhancement

#60 Filling json
  src/database.json
  src/index.html
Labels: enhancement

#61 Prettify electron
  package-lock.json
  src/app.js
  src/index.html
  src/public/images/icon.png
  src/public/images/package.jpg
  src/public/images/package.png
  src/public/javascripts/main.js
  src/public/stylesheets/main.css
  src/testing.html
Labels: enhancement

#66 Reveal Changes
  Exports/Example.json
  src/constants.json
  src/index.html
  src/public/javascripts/communication.js
  src/public/javascripts/datainterfacing.js
  src/public/javascripts/dynamicloading.js
  src/public/javascripts/handler.js
  src/public/javascripts/main.js
  src/public/javascripts/testingtool.js
  src/public/stylesheets/main.css
  src/testPodServer.js
  src/testing.html
Labels: Big

#69 Rtc latency
  src/index.html
  src/public/javascripts/communication.js
  src/public/javascripts/handler.js
  src/testPodServer.js
Labels: bug
