Repository badgerloop-software/pod-dashboard, pull requests merged in 2019-03, with the labels that each got.

#23 Tcp helper functions
  package-lock.json
  package.json
  src/constants.js
  src/public/javascripts/communication.js
Labels: enhancement

#27 merging js files
  src/index.html
  src/public/javascripts/dropdown.js
  src/public/javascripts/focusClone.js
  src/public/javascripts/handler.js
  src/public/javascripts/main.js
  src/public/javascripts/tables.js
Labels: enhancement

#28 Updated directory tree
  README.md
Labels: enhancement

#26 Dynamic sensor adding
  .eslintrc.js
  Exports/Example.json
  Exports/README.md
  package-lock.json
  src/app.js
  src/cache.js
  src/constants.js
  src/database.js
  src/database.json
  src/index.html
  src/public/javascripts/DataInterfacing.js
  src/public/javascripts/dynamicLoading.js
  src/public/javascripts/handler.js
  src/public/javascripts/main.js
  src/public/stylesheets/main.css
Labels: Big

#29 Render max mins
  src/database.json
  src/public/javascripts/dynamicLoading.js
Labels: enhancement

#31 Misc bug fixes
  README.md
  src/cache.js
  src/index.html
  src/public/javascripts/handler.js
  src/public/javascripts/main.js
  src/public/javascripts/testingTool.js
  src/public/stylesheets/main.css
  src/testing.html
Labels: bug

#32 Making dropdowns dynamic
  README.md
  package-lock.json
  src/index.html
  src/public/javascripts/dynamicLoadingDropdowns.js
  src/public/javascripts/handler.js
  src/public/javascripts/main.js
  src/testing.html
Labels: enhancement

#33 Convert config to json
  src/constants.js
  src/constants.json
  src/index.html
  src/public/javascripts/DataInterfacing.js
  src/public/javascripts/communication.js
  src/public/javascripts/config.js
  src/public/javascripts/dynamicLoading.js
  src/public/javascripts/dynamicLoadingDropdowns.js
  src/public/javascripts/generateLineChart.js
  src/public/javascripts/handler.js
  src/public/javascripts/main.js
  src/public/stylesheets/main.css
Labels: enhancement

#35 Fixed overflow
  src/public/javascripts/dynamicLoading.js
  src/public/javascripts/dynamicLoadingDropdowns.js
  src/public/javascripts/main.js
Labels: bug

#36 Ethan's favorite PR
  src/testPodServer.js
Labels: wontfix

#37 Renamed files, fupdated directory chart
  README.md
  src/index.html
  src/public/javascripts/charthandling.js
  src/public/javascripts/datainterfacing.js
  src/public/javascripts/dynamicloading.js
  src/public/javascripts/testingtool.js
  src/public/stylesheets/main.grid.css
  src/public/stylesheets/testingtool.grid.css
  src/testing.html
Labels: enhancement
